<?php

namespace App\Models\MarkerResources;

use App\Models\Marker;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class MarkerPhoto extends Model {
    use HasFactory;

    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($photo) {
            Storage::delete(str_replace('storage', 'public', $photo->url));
        });
    }

    public function marker() {
        return $this->belongsTo(Marker::class);
    }
}
